name: Docker Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-docker-windows:
    name: Docker Windows tests
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build image
        run: |
          docker build -t tools-base -f ./.ci/Dockerfile.windows .

      - name: Run Test
        run: |
          docker run -it --rm --name tools-base-test tools-base
