name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      PYTEST_ADDOPTS: "--color=yes" # colors in pytest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Set up cache
      uses: actions/cache@v2
      id: cache
      with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependencies
      run: |
        pipx install poetry
        poetry config virtualenvs.in-project true
        poetry install

    - name: Test with pytest
      run: |
        poetry run pytest

    - name: Run the setup script
      run: |
        poetry run python main.py --debug

    - uses: actions/upload-artifact@v3
      with:
        name: logs
        path: tools.log
